language: python
python:
  - 2.6
  - 2.7
  - 3.2
  # - 3.3  # not on travis yet
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests
